[32mINFO    [0m root:task_utility.py:14 Executing create task api
[32mINFO    [0m root:task_utility.py:15 Sending the POST request http://localhost:5000/tasks
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:226 Starting new HTTP connection (1): localhost:5000
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:433 http://localhost:5000 "POST /tasks HTTP/1.1" 200 23
[32mINFO    [0m root:task_utility.py:18 Got the status  code as 200
[32mINFO    [0m root:task_utility.py:24 {'task_id': 'd3os5DEI'}
[32mINFO    [0m root:task_utility.py:25 Created Task_id is :: d3os5DEI
[32mINFO    [0m root:test_task_post.py:17 Executing completed Task API
[32mINFO    [0m root:test_task_post.py:18 Sending the POST request with task id d3os5DEI
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:226 Starting new HTTP connection (1): localhost:5000
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:433 http://localhost:5000 "POST /tasks/d3os5DEI/completed HTTP/1.1" 200 2
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:226 Starting new HTTP connection (1): localhost:5000
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:433 http://localhost:5000 "GET /tasks/d3os5DEI HTTP/1.1" 200 38
[32mINFO    [0m root:test_task_post.py:20 Task status completed True