{"name": "test_deleted_taskid", "status": "failed", "statusDetails": {"message": "AssertionError: Testing get task with deleted it didn't work\nassert <Response [404]> == ''", "trace": "self = <test_endpoint.test_task_update.TestTaskUpdate object at 0x000001C80F98CC70>\n\n    def test_deleted_taskid(self):\n        logger.info(\"Executing GET Task API using deleted task id\")\n        logger.info('Sending the GET request with task id %s', TaskUtility.task_id)\n        response = TaskUtility().get_task_using_deleted_taskid(TaskUtility.task_id)\n        logger.info(\"Response is {response}\".format(response=response))\n>       assert response == \"\", \"Testing get task with deleted it didn't work\"\nE       AssertionError: Testing get task with deleted it didn't work\nE       assert <Response [404]> == ''\n\ntest_task_update.py:41: AssertionError"}, "attachments": [{"name": "log", "source": "37bbc21e-2283-4e75-b655-4dd53854ff90-attachment.txt", "type": "text/plain"}], "start": 1595227609108, "stop": 1595227611142, "uuid": "09324cda-b9f9-4f0f-bad5-3082dbc50303", "historyId": "c0b1084a1162b9a1c9d2ab2e2f5853c5", "testCaseId": "62703f655914c5e819bef57d2532ad8c", "fullName": "test_endpoint.test_task_update.TestTaskUpdate#test_deleted_taskid", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('create_and_get_task')"}, {"name": "parentSuite", "value": "test_endpoint"}, {"name": "suite", "value": "test_task_update"}, {"name": "subSuite", "value": "TestTaskUpdate"}, {"name": "host", "value": "LAPTOP-FMV55K7E"}, {"name": "thread", "value": "9672-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_endpoint.test_task_update"}]}