{"name": "test_modify_task_with_invalid", "status": "failed", "statusDetails": {"message": "AssertionError: Update task api dint updated the task\nassert <Response [404]> == ''", "trace": "self = <test_endpoint.test_task_update.TestTaskUpdate object at 0x0000022B03551820>\n\n    def test_modify_task_with_invalid(self):\n        logger.info(\"Executing Modify Task API\")\n        logger.info('Sending the POST request with task id %s', 456)\n        response = TaskUtility().update_task_using_invalid_id(456, update_task)\n        logger.info(\"Verify update task json is updated successfully expected %s ,Actual %s\", update_task, response)\n        logger.info(\"response\", response.text)\n>       assert response == \"\", \"Update task api dint updated the task\"\nE       AssertionError: Update task api dint updated the task\nE       assert <Response [404]> == ''\n\ntest_task_update.py:52: AssertionError"}, "attachments": [{"name": "log", "source": "98d97d6b-b19f-4516-83d3-b7b750046e4d-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "aa00e71b-9994-46c8-8a2c-cb90648c439c-attachment.txt", "type": "text/plain"}], "start": 1595227801666, "stop": 1595227803710, "uuid": "b56d3635-73b6-454d-a55a-b0881c385379", "historyId": "277152fc60587f62f70db64c9e90659b", "testCaseId": "7c4c2cc0b800fffec88275f4bd4b173d", "fullName": "test_endpoint.test_task_update.TestTaskUpdate#test_modify_task_with_invalid", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('create_and_get_task')"}, {"name": "parentSuite", "value": "test_endpoint"}, {"name": "suite", "value": "test_task_update"}, {"name": "subSuite", "value": "TestTaskUpdate"}, {"name": "host", "value": "LAPTOP-FMV55K7E"}, {"name": "thread", "value": "16612-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_endpoint.test_task_update"}]}