[32mINFO    [0m root:task_utility.py:14 Executing create task api
[32mINFO    [0m root:task_utility.py:15 Sending the POST request http://localhost:5000/tasks
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:226 Starting new HTTP connection (1): localhost:5000
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:433 http://localhost:5000 "POST /tasks HTTP/1.1" 200 23
[32mINFO    [0m root:task_utility.py:18 Got the status  code as 200
[32mINFO    [0m root:task_utility.py:24 {'task_id': '9Jbk4egN'}
[32mINFO    [0m root:task_utility.py:25 Created Task_id is :: 9Jbk4egN
[32mINFO    [0m root:test_task_update.py:19 Executing Modify Task API
[32mINFO    [0m root:test_task_update.py:20 Sending the POST request with task id 9Jbk4egN
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:226 Starting new HTTP connection (1): localhost:5000
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:433 http://localhost:5000 "PUT /tasks/9Jbk4egN HTTP/1.1" 200 23
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:226 Starting new HTTP connection (1): localhost:5000
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:433 http://localhost:5000 "GET /tasks/9Jbk4egN HTTP/1.1" 200 44
[32mINFO    [0m root:test_task_update.py:22 Verify update task json is updated successfully expected {'task': 'modifiedtask', 'completed': False} ,Actual {'task': 'modifiedtask', 'completed': False}