[32mINFO    [0m root:task_utility.py:14 Executing create task api
[32mINFO    [0m root:task_utility.py:15 Sending the POST request http://localhost:5000/tasks
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:226 Starting new HTTP connection (1): localhost:5000
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:433 http://localhost:5000 "POST /tasks HTTP/1.1" 200 23
[32mINFO    [0m root:task_utility.py:18 Got the status  code as 200
[32mINFO    [0m root:task_utility.py:24 {'task_id': 'DTYg0XlX'}
[32mINFO    [0m root:task_utility.py:25 Created Task_id is :: DTYg0XlX
[32mINFO    [0m root:test_task_get.py:20 Executing GET Task API
[32mINFO    [0m root:test_task_get.py:21 Sending the get request with task id DTYg0XlX
[32mINFO    [0m root:test_task_get.py:22 Static Variable %s
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:226 Starting new HTTP connection (1): localhost:5000
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:433 http://localhost:5000 "GET /tasks/DTYg0XlX HTTP/1.1" 200 39
[32mINFO    [0m root:test_task_get.py:24 Got the status  code as {'task': 'addtask', 'completed': False}
[32mINFO    [0m root:test_task_get.py:26 Verified created task json {'task': 'addtask', 'completed': False} with get task json {'task': 'addtask', 'completed': False}