[32mINFO    [0m root:task_utility.py:14 Executing create task api
[32mINFO    [0m root:task_utility.py:15 Sending the POST request http://localhost:5000/tasks
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:226 Starting new HTTP connection (1): localhost:5000
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:433 http://localhost:5000 "POST /tasks HTTP/1.1" 200 23
[32mINFO    [0m root:task_utility.py:18 Got the status  code as 200
[32mINFO    [0m root:task_utility.py:24 {'task_id': '37ic26l1'}
[32mINFO    [0m root:task_utility.py:25 Created Task_id is :: 37ic26l1
[32mINFO    [0m root:test_task_get.py:16 Executing GET Task API
[32mINFO    [0m root:test_task_get.py:17 Sending the get request with task id 37ic26l1
[32mINFO    [0m root:test_task_get.py:18 Static Variable %s
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:226 Starting new HTTP connection (1): localhost:5000
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:433 http://localhost:5000 "GET /tasks/37ic26l1 HTTP/1.1" 200 39
[32mINFO    [0m root:test_task_get.py:20 Got the status  code as {'task': 'addtask', 'completed': False}
[32mINFO    [0m root:test_task_get.py:22 Verified created task json {'task': 'addtask', 'completed': False} with get task json {'task': 'addtask', 'completed': False}